name:                generals-ui
version:             0.1.0.0
github:              "CharlesTaylor7/generals-ui"
license:             BSD3
author:              "Charles Taylor"
maintainer:          "charlestaylor95@gmail.com"
copyright:           "2020 Charles Taylor"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/CharlesTaylor7/generals-ui#readme>

dependencies:
- base >= 4.7 && < 5
- gtk3

library:
  source-dirs: src

executables:
  generals-ui-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - generals-ui

tests:
  generals-ui-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - generals-ui
